### ISSUE TITLE
Broken translation 3th November 2024

### ISSUE THREAD

**Issue by bittin** [agama-project/agama-weblate#5]
Hey!

testing with https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-installer.x86_64-10.0.0-openSUSE-Build25.171.iso today as i promised to do some more testing today

if you change to another language it does not get applied and you still get English only

**Comment by imobachgs** [comment]
Please, let's continue in https://github.com/agama-project/agama/issues/1724.

**Comment by bittin** [comment]
> Please, let's continue in [agama-project/agama#1724](https://github.com/agama-project/agama/issues/1724).

alright
